clean:
	./gradlew clean

build:
	./gradlew clean build

run:
	./gradlew run --args="\"src/test/resources/filepath1.json\" \"src/test/resources/filepath2.json\""

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain

.PHONY: build
